{
    "panelType": "xboard",
    "panels": {
        "mihomo": [
            {
                "url": "https://admin.shulaiyun.top",
                "description": "树赖加速器"
            }
        ]
    },
    "onlineSupport": [
        {
            "url": "https://admin.shulaiyun.top",
            "description": "在线客服",
            "apiBaseUrl": "https://admin.shulaiyun.top",
            "wsBaseUrl": "wss://admin.shulaiyun.top"
        }
    ],
    "proxy": []
}
