xboard:
  # å¿…é¡»æ˜¯ mihomo
  provider: mihomo
  
  remote_config:
    sources:
      - name: default_source
        # ğŸ‘‡ å¡«ä½ åˆšæ‰æ˜¾ç¤ºæˆåŠŸçš„é‚£ä¸ªé“¾æ¥ï¼
        url: https://app.shulaiyun.top/config.json
        priority: 100

  app:
    title: æ ‘èµ–åŠ é€Ÿå™¨
    # å¡«ä½ çš„é¢æ¿åŸŸå
    website: admin.shulaiyun.top
  
  subscription:
    prefer_encrypt: false
    # å¡«ä½ çš„é€šè®¯å¯†é’¥
    decrypt_key: 689789qqqqqqqq999

  security:
    obfuscation_prefix: "" 
    user_agents:
      api_encrypted: Mozilla/5.0 (compatible; XBoard-App/1.0)
      domain_racing_test: FlClash/1.0 (Domain Racing Test)
